name: Docker Image CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: $DOCKER_USERNAME
        password: $DOCKER_TOKEN

    - name: Build the Docker image
      run: docker build . -t points/interview-test-server:latest

    - name: Publish the docker image
      run: docker push points/interview-test-server:latest
